version: '3.9'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/usr/src/app
    command: npm start

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    command: npm start
